### ISSUE TITLE
Adding noise to step size?

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#10]
migrated from https://github.com/TuringLang/Turing.jl/issues/268

**Comment by xukai92** [comment]
Reference: end of Section 3.2 and end of Section 4.2 of (Neal, 2011)

**Comment by xukai92** [comment]
@yebai Do you still want it given the fact that it's on the to-remove list of Stan (https://github.com/stan-dev/stan/issues/2183)?

**Comment by yebai** [comment]
Hmm, quite interesting. I haven't tried this trick myself and doesn't really know whether it's intended to solve the high-curvature problem. My impression is that random jittering helps break periodicity in certain cases. We can probably leave this out of AHMC 0.2 then.

**Comment by xukai92** [comment]
Actually I just implemented it, it's very easy to add in our current abstraction. What I will do is leaving it as disable for default. Maybe we can do some experiments on this later.

**Comment by yebai** [comment]
Cool - sounds good.
