### ISSUE TITLE
Unify `Trajectory` type for static, dynamic HMC samplers. 

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#103]
We have the following nice composable interface for `NUTS` at the moment

```julia
p = NUTS{Multinomial,GeneralisedNoUTurn}(int)
```
where `NUTS` is a subtype of `DynamicTrajectory`. Maybe we can also unify `StaticTrajectory` and `DynamicTrajectory` via introducing a `Static` type and  a `MetropolisTS` trajectory sampler (with the final point as an MH proposal), i.e.

```julia
struct Static{T<:Integer} <: AbstractTerminationCriterion
    n_leapfrog::T
end

struct MetropolisTS <: AbstractTrajectorySampler end

# dynamic HMC with Multinomial sampling and generalised No-U-Turn. 
nuts = Trajectory{MultinomialTS,GeneralisedNoUTurn}(int)

# static HMC with a Multinomial sampling
hmc_Multinomial = Trajectory{MultinomialTS,Static}(int)

# standard HMC with an MH correction step
hmc= Trajectory{MetropolisTS,Static}(int)

```

We can also use integration time instead of a number of leapfrog steps in the `Static` type. This allows us to use `Trajectory` to construct all common HMC samplers including HMC, HMCDA and NUTS.

**Comment by xukai92** [comment]
I will do https://github.com/TuringLang/AdvancedHMC.jl/issues/102 first and see how to unify them later.

**Comment by xukai92** [comment]
After working on the spiral idea for a bit I realise that what we really need to do is treat the transition kernel as a seperate type.
```julia
sturct Kernel{T<:AbstractTrajectory,S<:AbstractTrajectorySampler,F<:AbstractRefreshment}
t::T
s::S
f::F
end
```

The current `NUTS{MultinomialTS,GeneralisedNoUTurn}` should be `Kernel(NUTS{GeneralisedNoUTurn}, MultinomialTS())` where `f` by default is set to be the completely refreshment.

By explicitly dispatch over `transition()` over `Kernel`, we can also the compelte control of a complete transition.

PS: We can also provide a composite kernel somehow. This is useful to combine a multinomial step + a MH step. Or maybe it's overcomplicated and we could introduce a specific type for this.

**Comment by yebai** [comment]
Closed by https://github.com/TuringLang/AdvancedHMC.jl/pull/245
