### ISSUE TITLE
Add AHMC composable interface to README

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#104]
There is a nice description of the composable interface in the StanCon submission. We should make it available somewhere, e.g. the README file. 

https://xuk.ai/software/StanCon-AHMC.pdf

**Comment by xukai92** [comment]
Sure. I will do an update soon. Maybe add some highlights in the README.md as well. Like GPU-support?

**Comment by yebai** [comment]
Would be cool to to have an GPU example.

**Comment by xukai92** [comment]
One more TODO for this
> Would be great if someone could document these various options btw. - Will

**Comment by xukai92** [comment]
Reminder for myself: do remeber to reuse this example: https://github.com/TuringLang/AdvancedHMC.jl/pull/90

**Comment by xukai92** [comment]
[StanCon-AHMC.pdf](https://github.com/TuringLang/AdvancedHMC.jl/files/3730367/StanCon-AHMC.pdf)

Just to save the poster in the AHMC repo.

**Comment by xukai92** [comment]
> One more TODO for this
> 
> > Would be great if someone could document these various options btw. - Will

Reuse the table in our draft.
