### ISSUE TITLE
Add NUTS diagnostics 

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/AdvancedHMC.jl#118]
Several people on Slack asked for better divergence diagnostics of NUTS.

Kusti Skyten wrote:
Divergent transitions https://mc-stan.org/bayesplot/articles/visual-mcmc-diagnostics.html#divergent-transitions are useful for choosing between equivalent formulations of a model with a better geometry for the posterior. Here's all the diagnostics in DHMC: https://github.com/tpapp/DynamicHMC.jl/blob/master/src/diagnostics.jl. AHMC seems to only have EBFMI (haven't looked that carefully at the code though).

Seth Axen wrote:
I also remember the output of AHMC's EBFMI very different from e.g. ArviZ. I haven't looked at it in detail yet though.

**Comment by jonasmac16** [comment]
#50

**Comment by jonasmac16** [comment]
#50

**Comment by xukai92** [comment]
I believe the cited Stan article or Sec. 6.2 of Betancourt  corresond to the `numerical_error` filed of elements in `stats`

**Comment by sethaxen** [comment]
I confirmed that there is a problem with the implementation of `EBFMI`. Its values are huge (it's supposed to be between 0 and 1 IIR, with lower than 0.3 being considered quite bad). It's an easy fix though. The numerator is supposed to be a mean, so it just needs to be divided by `length(Es) - 1`.

**Comment by xukai92** [comment]
Yes you are right. I should not have used `var` in the denumerator actually... Should be a summation too. Nice catch!

**Comment by xukai92** [comment]
In other words, it should be off by `1 / length(Es)` (not `1 / (length(Es) - 1)`).

**Comment by sethaxen** [comment]
The numerator is a summation over `n=length(Es)-1`, while the denominator is a summation over `n+1`. `var` in Julia defaults to `correction=true`, which would introduce a factor of `n`, so no, I think `var` is appropriate. FWIW, this is how `var` in R works and that's what RStan's implementation uses.

**Comment by xukai92** [comment]
Good point. I will make a PR to fix it.

**Comment by sethaxen** [comment]
Is `numerical_error` now completely equivalent to an indicator of divergent transition?

**Comment by xukai92** [comment]
If an `Inf` or `NaN` is treated as an infinte density then yes.
