### ISSUE TITLE
Add more statistics

### ISSUE THREAD

**Issue by sethaxen** [TuringLang/AdvancedHMC.jl#123]
PyMC3 has a comprehensive set of NUTS statistics [here](https://docs.pymc.io/api/inference.html#pymc3.step_methods.hmc.nuts.NUTS), some of which are missing from AdvancedHMC and would be nice to have returned when applicable. Here are the AdvancedHMC (=>PyMC3) ones that currently match up:
- step_size => step_size_bar (no jitter)
- n_steps => tree_size
- acceptance_rate => mean_tree_accept
- log_density => model_logp
- hamiltonian_energy => energy
- tree_depth => depth
- numerical_error => diverging (I think these technically aren't the same)

AdvancedHMC also has:
- is_accept

PyMC3 also has:
- energy_change: The difference in energy between the start and the end of the trajectory. For a perfect integrator this would always be zero.
- max_energy_change: The maximum difference in energy along the whole trajectory.
depth: The depth of the tree that was used to generate this sample
- tune: This is True, if step size adaptation was turned on when this sample was generated.
- step_size: The step size used for this sample.

The proposal is to add the following stats:
- hamiltonian_energy_error => energy_change
- max_hamiltonian_energy_error => max_energy_change
- is_adapt => tune
- step_size => step_size
- step_size_bar => step_size_bar

The latter two involving a renaming.

**Comment by xukai92** [comment]
Looks good to me. Should be straight forward to add. Do you want to make a PR for this?

**Comment by sethaxen** [comment]
Certainly!

**Comment by sethaxen** [comment]
Fixed by #124
