### ISSUE TITLE
Improve AHMC's documentation 

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#128]
The documentation for AHMC is currently sparse. Maybe we can improve the doc after AHMC API gets a bit more stable. For a good reference, see e.g. 
 https://docs.pymc.io/api/inference.html#pymc3.step_methods.hmc.nuts.NUTS

**Comment by xukai92** [comment]
I plan to do a major update of documentation (including https://github.com/TuringLang/AdvancedHMC.jl/issues/104) after the current two PRs (#117 and #124) are merged.

**Comment by xukai92** [comment]
I will fix #104 first for README. I think the best way to provide a good API documentation is still via Documenter.jl

**Comment by yebai** [comment]
Closed by #286
