### ISSUE TITLE
Modular design for refreshing momentum variables

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#13]
We should try to have a modular interface for different momentum refreshment methods (e.g. partial refreshments in [Neal 2011](https://arxiv.org/pdf/1206.1901.pdf))

**Comment by xukai92** [comment]
The current refresh function is here: https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/hamiltonian.jl#L113.

What's a sensible way to modularise the behaviour? Here are few thoughts / options
1. Parameterize `Hamiltonian`
2. Add another dedicated struct `Refreshment`
    - Then we can implement a parametric `Transition` that consists `Trajectory` and `Refreshment`.

Seems like 2 is btter.

**Comment by yebai** [comment]
I have been thinking about replacing the `metric::M` field of `Hamiltonian` with a more generic design, in a way similar to `ℓπ::Tlogπ`. 

```julia

struct Hamiltonian{M<:AbstractMetric, Tlogκ, T∂logπ∂θ}
    ℓκ::Tlogκ
    ℓπ::Tlogπ
    ∂ℓπ∂θ::T∂logπ∂θ
end
```

Then we can define different `refresh` functions for each `Tlogκ`. I think this design is similar to approach 2 but without an explicit `Refreshment` type.

**Comment by xukai92** [comment]
- What is `Tlogκ` to be more specific? Is it functions or something else?
- I feel the type of kinect energy is orthogonal to how a momentum variable is refreshed.

**Comment by yebai** [comment]
> What is Tlogκ to be more specific? Is it functions or something else?

`Tlogκ` can be a `Distribution` object, e.g. a multivariate `Gaussian` for standard HMC algorithms. 

> I feel the type of kinect energy is orthogonal to how a momentum variable is refreshed.

Yes, but we can make it parametric so that different `refresh/rand` functions can be called.

**Comment by xukai92** [comment]
> Tlogκ can be a Distribution object, e.g. a multivariate Gaussian for standard HMC algorithms.

I guess it's possible. We can even start with replacing the internal of `metric`` via `Distributions` objects as a first step. But I'm not sure how it generalise to say Riemannian  manifold HMC.

> Yes, but we can make it parametric so that different refresh/rand functions can be called.

The question is do we want to make refresh methods as parameter of kinect energy, or we want to make it as parameter of transition, or neither of them but to make the function take another argument and dispatch over structs.

**Comment by xukai92** [comment]
I personally prefer to add such a type to the Transition struct. But I haven't read through the paper I just send and see if we can still implement that using this abstraction.

**Comment by xukai92** [comment]
I have a design which can solve this issue as well as simplifying things like jittered leapfrog integrator. The key observation here is to decouple 1) trajectory building from 2) any *preparation steps* for it. Here preparation steps includes
- refresh momentum
- jitter leapfrog step size
Therefore, I proposed the following design
1. We introduce a type `Kernel` as below
```julia
struct Kernel
    r::AbstractRefreshment
    t::AbstractTrajectory
end
```
2. We use a function `transit` that returns a `Transition` type as below
```julia
function transit(::Kernel, ...)
    r = refresh(...)
    integrator = jitter(...)
    z, tstat = sample(...)
    return Transition(z, tstat)
end
3. In above, `sample` is renamed from the current `transition` function, which samples a phase point by building a trajecotry.

**Comment by xukai92** [comment]
Closed by https://github.com/TuringLang/AdvancedHMC.jl/pull/247
