### ISSUE TITLE
About the function returns the gradient of the likelihood 

### ISSUE THREAD

**Issue by wupeifan** [TuringLang/AdvancedHMC.jl#134]
In the MWE it seems that function which evaluates the gradient of the likelihood also returns the likelihood value. Is it possible to avoid that? Do I have to code a function that returns both of them together? I ask this because somehow I can write out the gradient without evaluating the whole function...

**Comment by xukai92** [comment]
HMC algorithm needs the log density still. So you will have to code that no matter what.

**Comment by wupeifan** [comment]
I do have the code for likelihood itself and I just want to avoid more function wrapping... (BTW a similar package, DynamicHMC.jl, does not require the density itself)
A stupid question here -- in constructing the Hamiltonian the log density is essentially called twice, right?

**Comment by xukai92** [comment]
The intention here to return a tuple is for saving computation as much as possible.

When constructing Hamiltonian the function are not called.
