### ISSUE TITLE
Make API doc avaiable at turing.ml

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#138]
@cpfiffer  mentioned it's not difficulty to use Documenter.jl to make the API avaiable in the Turing doc (https://github.com/TuringLang/AdvancedHMC.jl/pull/133#issuecomment-554792582)

**Comment by cpfiffer** [comment]
I can try to add this sometime soon.

**Comment by xukai92** [comment]
Cool. Thanks!

**Comment by cpfiffer** [comment]
This should be addressed once https://github.com/TuringLang/Turing.jl/pull/1022 goes through.

**Comment by cpfiffer** [comment]
The documentation for AdvancedHMC is now available here:

https://turing.ml/dev/docs/library/advancedhmc/

**Comment by yebai** [comment]
As @cpfiffer mentioned, this is fixed in TuringLang/Turing.jl#1022
