### ISSUE TITLE
customize the number of n_steps

### ISSUE THREAD

**Issue by wupeifan** [TuringLang/AdvancedHMC.jl#144]
The upper bound seems to be 10, which leads to 2^10 steps.
For the problem I have it is a bit slow to compute the integration with so many steps while drawing a substantial amount of samples. Are there any ways to customize the upper bound of `n_steps`?

**Comment by xukai92** [comment]
The signature is `NUTS(integrator; max_depth::Int=...)`. You can find it via `@doc NUTS`.

**Comment by wupeifan** [comment]
Are there any reasons that this upper bond is 10? Is there any literature that I can check?

**Comment by xukai92** [comment]
It's just the default one used in Stan which tends to be good enough for most of the problems without using too much computation.
