### ISSUE TITLE
Support DiffEq ODE integrators

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#145]
@ChrisRackauckas pointed out a paper (https://arxiv.org/abs/1912.03253) that uses the Calvo and Sanz-Sara methods in HMC. These integrators are already implemented in DiffEq (https://docs.juliadiffeq.org/latest/solvers/dynamical_solve/#Symplectic-Integrators-1). It would be nice to interface over them in AHMC.

**Comment by sethaxen** [comment]
Do you know if any of those correspond to the SHAKE/RATTLE symplectic integrators in the presence of geometric constraints?

**Comment by ChrisRackauckas** [comment]
They don't. Funnily enough, those are two I haven't gotten around to yet. Do they have a use case here? If they do I can get them done.

**Comment by sethaxen** [comment]
I may need them. I'm doing inference of protein structures. I expect due to collisions, my HMC trajectories will be littered with divergences that prevent accurate sampling. SHAKE/RATTLE are used in molecular dynamics to enforce fixed bond length constraints during sampling. I was planning to investigate whether they were appropriate for enforcing boundary constraints, in which case I could use them to sample my models with AdvancedHMC.

**Comment by ChrisRackauckas** [comment]
Let's call it done then. Also, implicit symplectic integrators would be able to do that too with a singular mass matrix. This would also be an algorithm that we would get for free here:

https://arxiv.org/abs/1911.05754

I'll see if there's any students who would find doing this research interesting. I know the set of benchmarks that one would get for free just by connecting these two libraries is essentially a free paper!

**Comment by ChrisRackauckas** [comment]
This should be a very big hint for anyone who wants to finish it: https://github.com/TuringLang/AdvancedHMC.jl/pull/146

**Comment by sethaxen** [comment]
Thanks so much @ChrisRackauckas!!

**Comment by ChrisRackauckas** [comment]
It's probably not complete. That PR was somewhat still WIP and needs tests, but it should be pretty close at least.

**Comment by xukai92** [comment]
I will make another PR to add tests and stuff soon.

**Comment by ChrisRackauckas** [comment]
If there's one thing to check, it's whether I put the right one as the momentum and the state equations. I may have flipped them.

**Comment by ChrisRackauckas** [comment]
BTW, if you help make sure this is running, I may have a research student in February do some investigation of the different methods in this context.

**Comment by IvanYashchuk** [comment]
It works now with #154

**Comment by ChrisRackauckas** [comment]
Probably can be closed now. Let's try to get a conference paper showcasing these methods 👍 . I might recruit a student to do some testing now. Thanks @IvanYashchuk for pushing it over the line! Let's get in touch over the Slack and get a channel going for paper efforts.

**Comment by yebai** [comment]
@xukai92 and myself are also looking at alternative integrators for solving Hamiltonian dynamics, particularly those parallelizable, might be interesting to discuss jointly.

**Comment by ChrisRackauckas** [comment]
I don't think there are very good parallel symplectic ODE solvers out there, but you can use RootedTrees.jl and a global optimizer kind of like I did in https://arxiv.org/abs/1804.04344 to derive one. I was going to do this to derive multi-GPU ODE solvers for first order ODEs, but if you want them, then hey, might be more fun to do this as a collab :).

**Comment by xukai92** [comment]
Thanks for the reference @ChrisRackauckas. Let me create a channel to discuss this further.
