### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#153]

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by xukai92** [comment]
Let's comment on the PR commit to trigger Julia registrator in the future, e.g. https://github.com/TuringLang/AdvancedHMC.jl/commit/514b33d170f95d17194433bfdc00e65e035b5bb9#commitcomment-36663461.
