### ISSUE TITLE
More robust and modular way of detecting divergence 

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#16]
Approximation error of leapfrog integration (i.e. accumulated Hamiltonian energy error) can sometimes explode, for example when the curvature of the current region is very high. This type of approximation error is sometimes called `divergence` [1] since it shifts a leapfrog simulation away from the correct solution. 

In Turing, this type of errors is currently caught a relatively ad-hoc function called `is_valid `, 

https://github.com/TuringLang/AdvancedHMC.jl/blob/734c0fa6d802a852d6b0bff7fc9f70a049a3f367/src/integrator.jl#L7

`is_valid` can catch cases where one or more elements of the parameter vector is either `nan` or `inf`. This has several drawbacks

- it's not general enough for catching all leapfrog approximation errors, e.g. when the parameter vector is valid but Hamiltonian energy is invalid.
- it may be delayed because numerical errors can appear in Hamiltonian energy earlier than in parameter vectors
- it's hard to propagate the exception around, i.e. at the moment we use a heuristic to find the previous valid point before approximation/numerical error happens
   - https://github.com/TuringLang/AdvancedHMC.jl/blob/734c0fa6d802a852d6b0bff7fc9f70a049a3f367/src/integrator.jl#L26
   - https://github.com/TuringLang/AdvancedHMC.jl/blob/734c0fa6d802a852d6b0bff7fc9f70a049a3f367/src/integrator.jl#L45

Therefore, we might want to refactor the current code a bit for a more robust mechanism for handling leapfrog approximation errors. Perhaps we can learn from the `DynamicHMC` implementation: 

https://github.com/tpapp/DynamicHMC.jl/blob/master/src/buildingblocks.jl#L168

[1]: Betancourt, M. (2017). A Conceptual Introduction to Hamiltonian Monte Carlo. arXiv preprint arXiv:1701.02434.

**Comment by yebai** [comment]
Update:

The current NUTS implementation rejects the whole Hamiltonian trajectory when numerical errors happen. In practice, a better way is to reject the subtree that contains the error (e.g. numerical error or divergent Hamiltonian). This will allow us to use part of the trajectory when numerical errors are detected. Keeping valid parts of the trajectory also improves the stability of the dual averaging algorithm, since rejecting a whole trajectory means throwing accept ratio `a` off a cliff suddenly (i.e. setting `a=0` from its current value). I suspect this is the reason for sharp fluctuation of dual averaging for NUTS. 

https://github.com/TuringLang/AdvancedHMC.jl/blob/734c0fa6d802a852d6b0bff7fc9f70a049a3f367/src/trajectory.jl#L85

**Comment by yebai** [comment]
Update:

The following 2 lines in `find_good_eps` are problematic. `(position, momentum)` shouldn't be refreshed during the initial search for stepsize (see Alg 4 of [Hoffman & Gelman, 2011][1])


https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/stepsize.jl#L16

https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/stepsize.jl#L18

[1]: http://arxiv.org/abs/1111.4246

**Comment by yebai** [comment]
Update: The following function should be removed: taking the last point from a `NoUTurnTrajectory` trajectory is not a valid approach to HMC since time-reversibility is no longer guaranteed. That is, `p(theta -> theta') = p(theta' -> theta)` no longer holds. It is possible to adjust the MH ratio to correct this, but it will almost reject all proposals since having a pair of `p(theta -> theta') ` is either 0 or 1 -- Hamiltonian proposals are deterministic. 

https://github.com/TuringLang/AdvancedHMC.jl/blob/734c0fa6d802a852d6b0bff7fc9f70a049a3f367/src/trajectory.jl#L118

**Comment by xukai92** [comment]
Regarding https://github.com/TuringLang/AdvancedHMC.jl/issues/16#issuecomment-470895756, does it mean we should reject the whole sub-tree?

Regarding https://github.com/TuringLang/AdvancedHMC.jl/issues/16#issuecomment-472167260, I guess I name the function wrong. This actually doing a slice sampling from the trajectory.

**Comment by yebai** [comment]
> Regarding #16 (comment), does it mean we should reject the whole sub-tree?

Yes, we should reject each trajectory increment that causes numerical error / divergent Hamiltonian.

**Comment by xukai92** [comment]
@yebai I think we are tackling this correctly in Turing; see https://github.com/TuringLang/Turing.jl/blob/master/src/inference/nuts.jl#L91-L93. An invalid numerical error would cause `H′` to be `Inf` and make `s′` equal to 0, which is the terminating condition of doubling tree in https://github.com/TuringLang/Turing.jl/blob/master/src/inference/nuts.jl#L153. 

I guess DynamicHMC follows a different abstraction from the NUTS paper so we didn't realise that before. What I can do is to add this divergence abstraction into the NUTS code to make it more readable if that makes sense.

**Comment by yebai** [comment]
> @yebai I think we are tackling this correctly in Turing; see https://github.com/TuringLang/Turing.jl/blob/master/src/inference/nuts.jl#L91-L93. An invalid numerical error would cause H′ to be Inf and make s′ equal to 0, which is the terminating condition of doubling tree in https://github.com/TuringLang/Turing.jl/blob/master/src/inference/nuts.jl#L153.

> I guess DynamicHMC follows a different abstraction from the NUTS paper so we didn't realise that before. What I can do is to add this divergence abstraction into the NUTS code to make it more readable if that makes sense.

I see - that makes sense. Introducing some abstractions for `divergence`, `dual averaging`, `(position, momentum)`, and other runtime information (e.g. tree-depth) sounds good.

**Comment by xukai92** [comment]
Good plan!

**Comment by yebai** [comment]
update:

The following line seems to be problematic, since the `leapfrog` integration should depend on the value of `v`. The current code will always simulate trajectory forward.

https://github.com/TuringLang/AdvancedHMC.jl/blob/64a72da3f05cb7be112883c83c1e9335f9b55887/src/proposal.jl#L101

**Comment by xukai92** [comment]
Nice catch! I'm wondering what's the best way to fix it, since we lost our interface of passing step size.
1. let `nt` has `forward_integrator` and `backward_integrator`?
2. pass `forward=true` in `step`?

**Comment by yebai** [comment]
update: 

the following line seems problematic too:

https://github.com/TuringLang/AdvancedHMC.jl/blob/a0af7ccc668a2a1e537dc5acdbe8c7bd22f11a86/src/integrator.jl#L45-L46

shouln't this be:

```julia
        θ_new = lf_position(lf.ϵ, h, θ, r)
        r_new, _is_valid = lf_momentum(i == n_steps ? lf.ϵ / 2 : lf.ϵ, h, θ_new, r)
```

**Comment by yebai** [comment]
> pass forward=true in step?

yip, I'll add a `fwd` flag in #49

**Comment by xukai92** [comment]
So what do we really want here? @yebai
