### ISSUE TITLE
Improving vectorized HMC implementaion

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#162]
Known issues
- NUTS is not supported
- A few bugs:
    1. Revert of phase points
- Multinomial sampling for static HMC is not supported

**Comment by sethaxen** [comment]
RE vectorized NUTS, see https://github.com/TuringLang/AdvancedHMC.jl/issues/140/

**Comment by xukai92** [comment]
All except from NUTS are resolved in https://github.com/TuringLang/AdvancedHMC.jl/pull/185
