### ISSUE TITLE
Consider introduce the `PhasePoint` type

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#17]

**Comment by yebai** [comment]
Do you mean `(θ, r)` (parameter, momentum) by `Point`?

**Comment by xukai92** [comment]
Yes, and possibly have some additional information just like https://github.com/tpapp/DynamicHMC.jl/blob/master/src/buildingblocks.jl#L124

**Comment by xukai92** [comment]
Closed by #51.
