### ISSUE TITLE
Merge metric and preconditoner

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#174]

**Comment by yebai** [comment]
As discussed, we plan to deprecate/remove `preconditioner` and encourage the user to use `WelfordCovEstimator` directly. For example, 

```julia
adaptor = StanHMCAdaptor(Preconditioner(metric), NesterovDualAveraging(0.8, integrator))
```

would become 

```julia
adaptor = StanHMCAdaptor(WelfordCovEstimator(metric), NesterovDualAveraging(0.8, integrator))
```

This design would simplify the type hierarchy, and  aligns better with the design for step size adaptors, e.g. `NesterovDualAveraging(0.8, integrator)`
