### ISSUE TITLE
Static trajectory multinomial HMC uses MH correction

### ISSUE THREAD

**Issue by bonStats** [TuringLang/AdvancedHMC.jl#198]
In the transition function for static trajectories, it appears a Metropolis-Hastings correction is being applied:
https://github.com/TuringLang/AdvancedHMC.jl/blob/f31dc17ac6611dfcc255ce9b903e8d127e17cd23/src/trajectory.jl#L178
even when the trajectory is a `StaticTrajectory{MultinomialTS}`. 

As far as I can tell from https://arxiv.org/pdf/1701.02434.pdf#subsection.A.2 I think the MH correction isn't required when a multinomial sample of the trajectory is used.

Is there something in my understanding or the code that I'm missing?

**Comment by xukai92** [comment]
Thanks for the issue. I think it's a bug. There shouldn't be any MH correction.

There is actually also another issue in how the trajectory is sampled for MultinomialTS, which I fixed in my local branch. I will create a PR to address both soon.

**Comment by bonStats** [comment]
Fixed in https://github.com/TuringLang/AdvancedHMC.jl/pull/199
