### ISSUE TITLE
Interface with AbstractMCMC.jl

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#211]
Example code of how the interface is supported in EllipticalSliceSampling.jl: https://github.com/TuringLang/EllipticalSliceSampling.jl/blob/master/src/abstractmcmc.jl

Support would also solve https://github.com/TuringLang/AdvancedHMC.jl/issues/184 and https://github.com/TuringLang/AdvancedHMC.jl/issues/101

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/AdvancedHMC.jl/pull/259
