### ISSUE TITLE
ϵ0 of JitteredLeapfrog is not adapted

### ISSUE THREAD

**Issue by Red-Portal** [TuringLang/AdvancedHMC.jl#218]
Hi,
Seems like the stepsize is not being adapted when using `JitteredLeapfrog`.
Guess this is because the member name for the stepsize parameter is `ϵ0` not `ϵ` as the others.
I highly doubt this is expected behavior but I just wanna check to be sure.
In theory, adaptation should also be applicable to `JitteredLeapfrog` right?

**Comment by Red-Portal** [comment]
Here's a working example.

```julia
using AdvancedHMC, Distributions, ForwardDiff

D = 10; initial_θ = rand(D)
ℓπ(θ) = logpdf(MvNormal(zeros(D), ones(D)), θ)
n_samples, n_adapts = 2_000, 1_000

metric = DiagEuclideanMetric(D)
hamiltonian = Hamiltonian(metric, ℓπ, ForwardDiff)

integrator = Leapfrog(2.0)

proposal = StaticTrajectory(integrator, 4)
adaptor = StanHMCAdaptor(MassMatrixAdaptor(metric), StepSizeAdaptor(0.8, integrator))

samples, stats = sample(hamiltonian, proposal, initial_θ, n_samples, adaptor, n_adapts; progress=true)

# Plot adaptation of stepsize 
Plots.plot([stat[:step_size] for stat in stats])
```
![2020-10-03_17-15](https://user-images.githubusercontent.com/18320033/94986760-45432f00-059c-11eb-93c9-770d5f44a3c5.png)
As we can see,

```julia
using AdvancedHMC, Distributions, ForwardDiff

D = 10; initial_θ = rand(D)
ℓπ(θ) = logpdf(MvNormal(zeros(D), ones(D)), θ)
n_samples, n_adapts = 2_000, 1_000

metric = DiagEuclideanMetric(D)
hamiltonian = Hamiltonian(metric, ℓπ, ForwardDiff)

# Leapfrog with 10% Jitter
integrator = JitteredLeapfrog(2.0, 0.1)

proposal = StaticTrajectory(integrator, 4)
adaptor = StanHMCAdaptor(MassMatrixAdaptor(metric), StepSizeAdaptor(0.8, integrator))

samples, stats = sample(hamiltonian, proposal, initial_θ, n_samples, adaptor, n_adapts; progress=true)

# Plot adaptation of stepsize 
Plots.plot([stat[:step_size] for stat in stats])
```
![2020-10-03_17-18](https://user-images.githubusercontent.com/18320033/94986776-6dcb2900-059c-11eb-9c9d-d6b211e0ebe1.png)

**Comment by trappmartin** [comment]
cc @xukai92

**Comment by yebai** [comment]
> Guess this is because the member name for the stepsize parameter is ϵ0 not ϵ as the others.
> I highly doubt this is expected behavior but I just wanna check to be sure.
> In theory, adaptation should also be applicable to JitteredLeapfrog right?

@Red-Portal Yes, adaption is applicable to `JitteredLeapfrog` in theory. We'll take a look at this issue soon. But if you know how to fix this issue, please do feel free to open a PR!

**Comment by Red-Portal** [comment]
@yebai Great. I would love to work on it right away, but sadly, I have a deadline right around the corner.
I'll open a PR if I have get some time to spare.

**Comment by xukai92** [comment]
This is a bug introduced when `ϵ` was renamed to `ϵ0` (https://github.com/TuringLang/AdvancedHMC.jl/pull/124). That PR also introduced `nom_step_size` to get the nominal integration step size but how that step size is updated is not properly handled.

**Comment by xukai92** [comment]
The (direct) fix would be to replace https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/sampler.jl#L17 by a function called `update_ nom_step_size` and handle different integrators correctly (we probably only need to handle jittered correctly and having a fallback to others).

**Comment by sethaxen** [comment]
Good find, @Red-Portal , I'll open a PR to fix this.
