### ISSUE TITLE
Modify link-out to IMP.hmc

### ISSUE THREAD

**Issue by sethaxen** [TuringLang/AdvancedHMC.jl#223]
I just notice that #164 updated the README with a link to [IMP.hmc](https://github.com/salilab/hmc), designated "Python interface". IMP.hmc does indeed use Python to interface between AdvancedHMC and something else, but that something else is a large Python/C++ package for protein structure determination. It does not make AdvancedHMC available to generic Python users. It's also a highly experimental package.

Personally, I think a Python interface would be rad (and would make IMP.hmc much simpler), but it's misleading to call IMP.hmc that.

**Comment by xukai92** [comment]
Thanks Seth! Can you fire a PR to make the description more properly?

**Comment by sethaxen** [comment]
Sure!
