### ISSUE TITLE
Sampling hangs on integer data

### ISSUE THREAD

**Issue by anhi** [TuringLang/AdvancedHMC.jl#229]
Hi,

I'm trying to fit a Weibull distrbution to input data that happen to be exact integers, but sampling doesn't terminate. Here is a reduced example:

```julia
using Turing, Distributions

@model weibull(x) = begin
    μ ~ Uniform(1, 10)
    σ ~ Uniform(1, 10)

    x ~ Weibull.(σ, μ)
end

w = Weibull(2, 4);
data = rand(w, 1000);
rounded = round.(data)
rounded_noisy = rounded + 0.01 .* rand(length(rounded));

# this works
chain = sample(weibull(data), NUTS(0.65), 1000, progress=true)
# this works, too
chain =  sample(weibull(rounded_noisy), NUTS(0.65), 1000, progress=true)
# this doesn't
chain =  sample(weibull(rounded), NUTS(0.65), 1000, progress=true)```
`

**Comment by luiarthur** [comment]
I think the issue might be due to rounded containing zeros. (Note that `logpdf(w, 0) == 0`)

If `rounded` does not contain any zeros, it also runs fine.

**Comment by anhi** [comment]
Ah, that makes perfect sense! You are absolutely right, so I'll close this issue.
