### ISSUE TITLE
HMC gives GPU compilation error

### ISSUE THREAD

**Issue by sharanry** [TuringLang/AdvancedHMC.jl#235]
I have been trying to infer parameters in a Flux model. I have previously successfully used AdvancedMH for this purpose. 

I am now trying to infer using a single step HMC (aka MALA) on GPU. However, I am facing some GPU compilation error.

I am aware of @sethaxen's https://github.com/TuringLang/AdvancedHMC.jl/pull/228 and @xukai92's https://gist.github.com/xukai92/5fdbc481e4c3360561d972647a690acd which attempt to vectorize NUTS-HMC and make Advanced HMC compatible with GPUs. However, I have tried using both of them and I still get the following GPU compilation issue.

Here is a self-contained demostration of the issue.
https://gist.github.com/sharanry/86d89d7d37594fc51a3da44e96cbd6ea

CC: @yebai

**Comment by xukai92** [comment]
It seems that the line numbers in the error msg in your gist do not match anything on the master branch. 
Can you also share you package versions as well to see which AHMC version you are using?

**Comment by sharanry** [comment]
@xukai92 
I have tried using both the latest release and [AdvancedHMC#iterativenuts](https://github.com/TuringLang/AdvancedHMC.jl/tree/iterativenuts). This notebook was run on [AdvancedHMC#iterativenuts](https://github.com/TuringLang/AdvancedHMC.jl/tree/iterativenuts)

**Comment by sethaxen** [comment]
@sharanry, iterative NUTS is still a WIP and has not been tested for the GPU yet. @xukai92's gist will probably be more useful.

**Comment by xukai92** [comment]
@sharanry Can you try my gist with the master branch with `UnitEuclideanMetric` first? 
I don't think I have yet tried `DiagEuclideanMetric`, which might be the issue here.

**Comment by sharanry** [comment]
> @sharanry Can you try my gist with the master branch with UnitEuclideanMetric first?
> I don't think I have yet tried DiagEuclideanMetric, which might be the issue here.

@xukai92 I tried that too and I get the following error.

```julia
ERROR: LoadError: MethodError: no method matching PhasePoint(::CuArray{Float32,1}, ::CuArray{Float32,1}, ::AdvancedHMC.DualValue{Float64,CuArray{Float64,1}}, ::AdvancedHMC.DualValue{Float32,CuArray{Float32,1}})
Closest candidates are:
  PhasePoint(::T, ::T, ::V, ::V) where {T, V} at C:\Users\Sharan Yalburgi\.julia\packages\AdvancedHMC\6lk7W\src\hamiltonian.jl:44
```

Looks like a `Float64` is creeping in from somewhere. Looking into it.

[Here](https://gist.github.com/sharanry/6026786104067508ad8b91e2d793322c) is the corresponding code.

**Comment by xukai92** [comment]
What the msg says is that your log density and its gradient are `Float64`.
With a quick look at your code, https://gist.github.com/sharanry/6026786104067508ad8b91e2d793322c#file-hmc_gpu_v0-1-jl-L121 seems to be suspicious - the `prior` you initialised should have used `Float64` by default and you are calling `logpdf(prior, params)` inside `log_pdf`, which should have gave you a promotion from `Float32` from other parts to `Float64`.

**Comment by sharanry** [comment]
Thanks for that!
Looks like logpdf of mvnormal is not typestable.

```julia
julia> using Distributions

julia> prior = MvNormal(5, Float32(1))
MvNormal{Float32,PDMats.ScalMat{Float32},FillArrays.Zeros{Float32,1,Tuple{Base.OneTo{Int64}}}}(
dim: 5
μ: 5-element Zeros{Float32}
Σ: Float32[1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0]
)


julia> typeof(logpdf(prior, randn(Float32, 5)))
Float64
```

**Comment by sharanry** [comment]
Enforcing `Float32` everywhere helped. Sampling works now. Thanks a ton for the help! @xukai92 @sethaxen
