### ISSUE TITLE
Error gradient

### ISSUE THREAD

**Issue by mahaa2** [TuringLang/AdvancedHMC.jl#243]
Hi, 
I am trying to use closed-form gradients, e.g,

function g(x::Vector{Float64})
	norm(x)^2	
end

function dg(x::Vector{Float64})
	2*x
end

metric = DiagEuclideanMetric(2)
h = Hamiltonian(metric, g, dg)
eps_init = find_good_stepsize(h, randn(2))

However, I get an error in eps_init accusing - "AssertionError: `typeof(gradient)`: Float64"

Any clues ? 

Thank you.

**Comment by xukai92** [comment]
Sorry for the late reply. The gradient is supposed to return a tuple of value and graident. In your case, it should be
```julia
function dg(x::Vector{Float64})
x, 2*x
end
```

**Comment by xukai92** [comment]
Please close this issue if the above solves your question. Thanks :)

**Comment by mahaa2** [comment]
Thanks
