### ISSUE TITLE
StanHMC-adaptor

### ISSUE THREAD

**Issue by mahaa2** [TuringLang/AdvancedHMC.jl#252]
Hi,

When the StanHMC-adaptor seems to be on, the algorithm search for higher posterior density first in a deterministic way, and after that, it starts to sample from the posterior. I am not sure about my claims, could you elucidate ? 

Thanks.

**Comment by yebai** [comment]
Not quite, AdvancedHMC does not search for the posterior mode. StanHMC-adaptor only adapts the mass matrix for the momentum variable, and the step-size for the leapfrog integrator, under an elaborate windowed adaption scheme.

**Comment by xukai92** [comment]
You can read more abou the details of the adaptation here: https://mc-stan.org/docs/2_18/reference-manual/hmc-algorithm-parameters.html
