### ISSUE TITLE
DynamicHMC is (~5 times) faster than Turing's HMC implementation

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#26]
Time used for collecting 2 million samples 
- Turing.NUTS: 3318.293540 seconds (33.35 G allocations: 1.299 TiB, 29.35% gc time)
- Turing.DynamicNUTS: 848.741643 seconds (7.86 G allocations: 251.076 GiB, 32.13% gc time)

using the following 

```julia

using DynamicHMC, Turing, Test

@model gdemo(x, y) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x ~ Normal(m, sqrt(s))
  y ~ Normal(m, sqrt(s))
  return s, m
end

mf = gdemo(1.5, 2.0)

@time chn1 = sample(mf, DynamicNUTS(2000000));

@time chn2 = sample(mf, Turing.NUTS(2000000, 0.65));

```

**Comment by mohamed82008** [comment]
On the type stability branch:
- NUTS: ` 20.769626 seconds (166.79 M allocations: 9.301 GiB, 19.40% gc time)`
- DynamicHMC: `27.478044 seconds (230.15 M allocations: 13.436 GiB, 18.68% gc time)`

**Comment by xukai92** [comment]
@mohamed82008 you mean a type stable Turing with Turing's HMC or this?

**Comment by mohamed82008** [comment]
No this is before this package, just using Turing HMC.

**Comment by xukai92** [comment]
Wow then we would have a lot more potential important still. I will do a simple integration of this package in the same way as DynamicHMC in Turing after I port all adaptation codes into this package. We will see how much we can get by doing that :D

**Comment by cpfiffer** [comment]
That's a pretty amazing improvement!

**Comment by xukai92** [comment]
Just did some quick test against DynamicHMC with 3ac4db1563b62fcc381abf9b5cfe4fb6852a8bdb. We are among the same speed now. 

|#samples|DynamicHMC|AdavancedHMC|
|-|-|-|
|10_000|14.57 / 5.59 | 12.47 / 2.58|
|100_000|24.16 / 13.36 | 23.84 / 11.96|
|500_000|80.29 / 55.00|88.38 / 61.43|

Numbers are in seconds with the first number being wrapping `@time` over Turing's `sample` function and the second number being wrapping `@time` over the packages' core `sample` function.

**Comment by trappmartin** [comment]
Could you re-run this using `@btime`? This way the time estimates would be more reliable as they are estimated for multiple calls while `time` is only a snapshot of a single call.

**Comment by yebai** [comment]
Updated comparison based on AHMC (7a0e42c) and Turing (TuringLang/Turing.jl@92a0e2a). 

```
julia> mf = gdemo(1.5, 2.0)
Turing.Model{Tuple{:s,:m},Tuple{:x,:y},getfield(Main, Symbol("###inner_function#382#10")),NamedTuple{(:x, :y),Tuple{Float64,Float64}},NamedTuple{(:x, :y),Tuple{Symbol,Symbol}}}(getfield(Main, Symbol("###inner_function#382#10"))(Core.Box(getfield(Main, Symbol("###inner_function#382#10"))(#= circular reference @-2 =#))), (x = 1.5, y = 2.0), (x = :nothing, y = :nothing))

julia> @time chn1 = sample(mf, DynamicNUTS(20000))
 18.991198 seconds (55.29 M allocations: 3.017 GiB, 6.91% gc time)

julia> @time chn2 = sample(mf, Turing.NUTS(20000, 0.65));
┌ Info: Finished 1000 adapation steps
│   typeof(adaptor) = AdvancedHMC.Adaptation.StanHMCAdaptor{AdvancedHMC.Adaptation.DensePreconditioner{Float64,AdvancedHMC.Adaptation.WelfordCov{Float64}},AdvancedHMC.Adaptation.NesterovDualAveraging{Float64}}
│   (τ.integrator).ϵ = 0.26506169649879274
└   h.metric = [0.397546, 0.850986]
┌ Info: Finished 20000 sampling steps in 6.903967957 (s)
│   typeof(h.metric) = AdvancedHMC.Adaptation.DenseEuclideanMetric{Float64,Array{Float64,1},Array{Float64,2},LinearAlgebra.UpperTriangular{Float64,Array{Float64,2}}}
│   typeof(τ) = AdvancedHMC.NUTS{AdvancedHMC.Leapfrog{Float64}}
│   EBFMI(Hs) = 19663.70513482061
└   mean(αs) = 0.7903777752674378
 11.790677 seconds (66.83 M allocations: 3.063 GiB, 11.18% gc time)
```

**Comment by xukai92** [comment]
What is Turing (TuringLang/Turing.jl@92a0e2a)? I think we need to update the grad function in Turing to work with master; see my branch https://github.com/TuringLang/Turing.jl/tree/kx/update-ahmc

**Comment by yebai** [comment]
> What is Turing (TuringLang/Turing.jl@92a0e2a)?

It's the current master branch.

**Comment by xukai92** [comment]
Oh I see. This is not even with the new AHMC PR.

**Comment by xukai92** [comment]
@yebai I tried a bit with master of AHMC. Also notice that the time differs for the first call and the second call.

```julia

julia> using Turing, DynamicHMC

julia> @model gdemo(x, y) = begin
         s ~ InverseGamma(2, 3)
         m ~ Normal(0, sqrt(s))
         x ~ Normal(m, sqrt(s))
         y ~ Normal(m, sqrt(s))
         return s, m
       end
gdemo (generic function with 3 methods)

julia> mf = gdemo(1.5, 2.0);

julia> @time chn1 = sample(mf, DynamicNUTS(20000));
MCMC, adapting ϵ (75 steps)
0.0019 s/step ...done
MCMC, adapting ϵ (25 steps)
5.6e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
0.0025 s/step ...done
MCMC, adapting ϵ (100 steps)
4.5e-5 s/step ...done
MCMC, adapting ϵ (200 steps)
3.7e-5 s/step ...done
MCMC, adapting ϵ (400 steps)
3.7e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
5.2e-5 s/step ...done
MCMC (20000 steps)
4.9e-5 s/step ...done
 15.209981 seconds (54.31 M allocations: 2.965 GiB, 8.18% gc time)

julia> @time chn1 = sample(mf, DynamicNUTS(20000));
MCMC, adapting ϵ (75 steps)
0.00022 s/step ...done
MCMC, adapting ϵ (25 steps)
6.2e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
6.0e-5 s/step ...done
MCMC, adapting ϵ (100 steps)
5.0e-5 s/step ...done
MCMC, adapting ϵ (200 steps)
5.1e-5 s/step ...done
MCMC, adapting ϵ (400 steps)
4.6e-5 s/step ...done
MCMC, adapting ϵ (50 steps)
5.5e-5 s/step ...done
MCMC (20000 steps)
4.9e-5 s/step ...done
  1.682974 seconds (11.80 M allocations: 840.035 MiB, 22.60% gc time)

julia> @time chn2 = sample(mf, Turing.NUTS(20000, 0.65); verbose=false);
  7.205303 seconds (44.96 M allocations: 2.256 GiB, 13.16% gc time)

julia> @time chn2 = sample(mf, Turing.NUTS(20000, 0.65); verbose=false);
  2.742800 seconds (25.31 M allocations: 1.318 GiB, 21.04% gc time)

julia> 
```

Looks it like someting to do with the memory allocation? The first time AHMC uses less memory than DHMC but for the second time the situation is the opposite. Maybe related to @mohamed82008's open PR?

**Comment by chriselrod** [comment]
> The first time AHMC uses less memory than DHMC but for the second time the situation is the opposite.

DynamicHMC's first time is also compiling the gradient for gdemo, while Turing.NUT's first time isn't. If you switch the order of your tests, does that pattern change?

How do both compare in terms of tree depth? If DynamicHMC manages to use shallower trees, that'd provide a hefty speed boost. DynamicHMC and AdvancedHMC use different regularized mass matrices, so it's possible once converges a little better than the other.

**Comment by xukai92** [comment]
> > The first time AHMC uses less memory than DHMC but for the second time the situation is the opposite.
> 
> DynamicHMC's first time is also compiling the gradient for gdemo, while Turing.NUT's first time isn't. If you switch the order of your tests, does that pattern change?

@chriselrod Good point! You are right here!

```julia
julia> using Turing, DynamicHMC

julia> @model gdemo(x, y) = begin
         s ~ InverseGamma(2, 3)
         m ~ Normal(0, sqrt(s))
         x ~ Normal(m, sqrt(s))
         y ~ Normal(m, sqrt(s))
         return s, m
       end
gdemo (generic function with 3 methods)

julia> mf = gdemo(1.5, 2.0);

julia> @time chn2 = sample(mf, Turing.NUTS(20000, 0.65); verbose=false);
 13.831420 seconds (67.09 M allocations: 3.381 GiB, 9.46% gc time)

julia> @time chn2 = sample(mf, Turing.NUTS(20000, 0.65); verbose=false);
  2.570398 seconds (28.25 M allocations: 1.441 GiB, 18.27% gc time)

julia> @time chn1 = sample(mf, DynamicNUTS(20000));
  7.086903 seconds (29.69 M allocations: 1.730 GiB, 10.71% gc time)

julia> @time chn1 = sample(mf, DynamicNUTS(20000));
  1.757307 seconds (11.93 M allocations: 847.161 MiB, 24.64% gc time)
```

> How do both compare in terms of tree depth? If DynamicHMC manages to use shallower trees, that'd provide a hefty speed boost. DynamicHMC and AdvancedHMC use different regularized mass matrices, so it's possible once converges a little better than the other.

Will check the tree depth. Both uses the dense preconditioning adapation.

**Comment by xukai92** [comment]
@chriselrod The gap is much smaller than the previous result shows actually. In fact, the way I build logdensity functions in Turing that are passed to AHMC and DHMC is slightly different. After this commit (https://github.com/TuringLang/Turing.jl/pull/849/commits/e7ef6ccf4dd8c5b9891c21cff411b002ba962198) which makes them same, the performance is like below:

```julia
julia> using Turing, DynamicHMC, BenchmarkTools

julia> @model gdemo(x, y) = begin
                s ~ InverseGamma(2, 3)
                m ~ Normal(0, sqrt(s))
                x ~ Normal(m, sqrt(s))
                y ~ Normal(m, sqrt(s))
                return s, m
              end

julia> mf = gdemo(1.5, 2.0);

julia> @time chn1 = sample(mf, DynamicNUTS(20000));
 17.641782 seconds (56.00 M allocations: 3.053 GiB, 7.57% gc time)

julia> @time chn2 = sample(mf, Turing.NUTS(20000, 0.8); verbose=false);
  6.330085 seconds (29.60 M allocations: 1.751 GiB, 13.27% gc time)

julia> @benchmark chn1 = sample(mf, DynamicNUTS(20000))
BenchmarkTools.Trial: 
  memory estimate:  845.87 MiB
  allocs estimate:  11907916
  --------------
  minimum time:     1.676 s (24.32% GC)
  median time:      1.720 s (26.35% GC)
  mean time:        1.740 s (25.91% GC)
  maximum time:     1.823 s (26.95% GC)
  --------------
  samples:          3
  evals/sample:     1

julia> @benchmark chn2 = sample(mf, Turing.NUTS(20000, 0.8); verbose=false)
BenchmarkTools.Trial: 
  memory estimate:  1015.94 MiB
  allocs estimate:  14586841
  --------------
  minimum time:     1.843 s (23.94% GC)
  median time:      1.871 s (25.63% GC)
  mean time:        1.902 s (25.66% GC)
  maximum time:     1.991 s (27.29% GC)
  --------------
  samples:          3
  evals/sample:     1
```

Also, I changed the tartget acceptance ratio to 0.8 as this is what DHMC used. @yebai
