### ISSUE TITLE
README example fails

### ISSUE THREAD

**Issue by jmsull** [TuringLang/AdvancedHMC.jl#295]
Hi, I am trying out AHMC for the first time and noticed that the README example doesn't work.

The line
```julia
metric = DiagEuclideanMetric(D)
```
gives the error:
```
ERROR: MethodError: no method matching DiagEuclideanMetric(::Int64)
Closest candidates are:
  DiagEuclideanMetric(::Int64, ::V) where {T<:Real, V<:AbstractVector{T}} at ~/.julia/packages/AdvancedHMC/9AC0k/src/metric.jl:44
  DiagEuclideanMetric(::Int64, ::A, ::A, ::A) where {T<:Real, A<:AbstractVector{T}} at ~/.julia/packages/AdvancedHMC/9AC0k/src/metric.jl:19
  DiagEuclideanMetric(::A) where {T<:Real, A<:AbstractVector{T}} at ~/.julia/packages/AdvancedHMC/9AC0k/src/metric.jl:35
```

Looks like there was an accepted argument change since this example was written?

**Comment by jmsull** [comment]
```julia
initial_ϵ = find_good_stepsize(hamiltonian, initial_θ)
```
Also gives

`ERROR: UndefVarError: find_good_stepsize not defined
`

**Comment by yebai** [comment]
@jmsull This might be because you are using a very old version of AdvancedHMC. Can you post which version of AHMC you are using? You can get this information by running `] st`.

**Comment by jmsull** [comment]
@yebai

Thanks for the reply - sorry, I must have made some package mistake somewhere (though I restarted after updating AHMC as instructed), now those things above work after updating and restarting Julia a second time.
```
st AdvancedHMC
[0bf59076] AdvancedHMC v0.3.6
```
However now there is an issue with the NUTS line?

```julia
proposal = NUTS{MultinomialTS, GeneralisedNoUTurn}(integrator)
ERROR: UndefVarError: NUTS not defined
```

This works fine though
```julia
proposal = AdvancedHMC.NUTS{MultinomialTS, GeneralisedNoUTurn}(integrator)
```
and it looks like `NUTS` should be exported when runninng  ```julia using AdvancedHMC```?
