### ISSUE TITLE
Register this package

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#33]
Will do after #31 gets merged.

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()

**Comment by xukai92** [comment]
@JuliaRegistrator register()

**Comment by xukai92** [comment]
@JuliaRegistrator register()

**Comment by xukai92** [comment]
@JuliaRegistrator register()

**Comment by xukai92** [comment]
@JuliaRegistrator register()

**Comment by yebai** [comment]
@JuliaRegistrator register()
