### ISSUE TITLE
Simplifying `Metric` types by using `AbstractPDMat`

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#34]
The following 3 types in `src/metric.jl`:

- https://github.com/TuringLang/AdvancedHMC.jl/blob/a0af7ccc668a2a1e537dc5acdbe8c7bd22f11a86/src/metric.jl#L16-L24

- https://github.com/TuringLang/AdvancedHMC.jl/blob/a0af7ccc668a2a1e537dc5acdbe8c7bd22f11a86/src/metric.jl#L41-L49

- https://github.com/TuringLang/AdvancedHMC.jl/blob/a0af7ccc668a2a1e537dc5acdbe8c7bd22f11a86/src/metric.jl#L3-L5

can be merged into one type using `AbstractPDMat`

```julia

struct EuclideanMetric{T<:Real,A<:AbstractPDMat{T}} <: AbstractMetric{T}
    M⁻¹     ::  A # contains dim, M⁻¹ and its Cholesky decomposition. 
    # Pre-allocation for intermediate variables
    _temp   ::  A
end
```

Reference: https://github.com/JuliaStats/PDMats.jl

**Comment by xukai92** [comment]
Got it!

**Comment by yebai** [comment]
Also, the `Metric._temp` can be removed if we introduce a `PhasePoint` type (see also https://github.com/TuringLang/AdvancedHMC.jl/issues/17):

```julia
z2::PhasePoint = rand_momentum(rng::AbstractRNG, h::Hamiltonian, z::PhasePoint)
```

Since `rand_momentum` can perform in-place update for `z::PhasePoint`.  However, I'm not sure whether this is necessary since moment variables are not updated as frequent as position variables.

**Comment by xukai92** [comment]
@yebai There is some werid design in PDMats.jl that is not consistent with AHMC. Basically `PDiagMat` will take a vector and compute the `inv` it - not `sqrt` it, which is what we need in AHMC.

**Comment by yebai** [comment]
> @yebai There is some werid design in PDMats.jl that is not consistent with AHMC. Basically PDiagMat will take a vector and compute the inv it - not sqrt it, which is what we need in AHMC.

Can we create a wrapper type for `AbstractPDMat`? For example

```julia

type Metric{T<:Real,M<:AbstractPDMat{T},V<:AbstractVector{T}} <: AbstractPDMat{T}
 m::M
 sqrt_diag::V                     # the vector of diagonal elements
end
```

**Comment by xukai92** [comment]
This is almost the same is current Metric types right? And the current version we have would be more memory friendly than this because we only store the original M inverse & its sqrt or chol if needed. While warpping things like you proposed, m would store useless invese matrix for diagonal.

**Comment by yebai** [comment]
Ah, I see. Can you remind me why we need `sqrt_diag`?

**Comment by xukai92** [comment]
See: https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/adaptation/precond.jl#L342

Reference: https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/hamiltonians/diag_e_metric.hpp#L53

**Comment by yebai** [comment]
`sqrt` seems like a cheap operation (see [wiki](https://en.wikipedia.org/wiki/Computational_complexity_of_mathematical_operations#Arithmetic_functions)), maybe we don't need to cache it? I don't have a strong feeling here - our `Metric` interface looks good to me actually.

**Comment by xukai92** [comment]
> `sqrt` seems like a cheap operation (see [wiki](https://en.wikipedia.org/wiki/Computational_complexity_of_mathematical_operations#Arithmetic_functions)), maybe we don't need to cache it? 
If we remove that filed then the interface is a little bit inconsistent?

> I don't have a strong feeling here - our `Metric` interface looks good to me actually.
I agree. I cleaned it up a bit. There was some unused functions that makes the code look worse than it should be.

I prefer to not change it :D

**Comment by xukai92** [comment]
Shall we close this issue then.
