### ISSUE TITLE
Samples during adaption phase

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#35]
Maybe we should make the `sample` function not return those samples by default (and support an optional keyword for it)?

**Comment by yebai** [comment]
yes, but let's consider fix these issues altogether in https://github.com/TuringLang/Turing.jl/issues/723

**Comment by yebai** [comment]
Is this issue resolved in AHMC now?

**Comment by xukai92** [comment]
AHMC currently doesn't deal with dropping adaption phase samples at all. This is done in Turing side. I'm not sure if we want to support it here at all? How do you think?

**Comment by xukai92** [comment]
We can also implement it here. So Turing side can just droping adaption samples via passing a keyword argument to AHMC. I just don't know which one is better (this or the current one).

**Comment by yebai** [comment]
Maybe  we can create a keyword argument in AHMC, the use it optionally in other packages like Turing.

**Comment by cpfiffer** [comment]
I think Turing should maintain it's current behavior by dropping the samples at the end of sampling. If it's done strictly on the AHMC side, then the NUTS/HMC code won't work so well in Gibbs. 

It is a good idea to include a keyword for AHMC though, if only to give users more options for raw AHMC.

**Comment by xukai92** [comment]
Also, if AHMC knows those samples will be dropped, it doesn't have to store them at all, which could be a potential performance improvement.

**Comment by xukai92** [comment]
> ... by dropping the samples at the end of sampling

Maybe Turing side should not keep the samples during adaptation at all if they were to be dropped in the end? @cpfiffer

**Comment by cpfiffer** [comment]
That's really a design choice. You could move the adaptation stuff to `sample_init!` if you wanted to. A question I'd have is related to Gibbs: Do you need to run the other component samplers while HMC is running, or can it adapt independently? If it can adapt independently then we can just put the adaptation phase in `sample_init!` and everything's cool. Alternatively, if they need to be run together, we'd have to modify the `Gibbs` code to run the adaptation cycle ahead of time with all the component samplers.

**Comment by yebai** [comment]
>  question I'd have is related to Gibbs: Do you need to run the other component samplers while HMC is running, or can it adapt independently? If it can adapt independently then we can just put the adaptation phase in sample_init! and everything's cool.

It's likely this won't work well, because it'll only adapt a local covariance conditioned on variables not updated by HMC. 

> Maybe Turing side should not keep the samples during adaptation at all if they were to be dropped in the end? @cpfiffer

I think it's better to keep the samples during adaption, and optionallly drop them when sampling finishes. This is simpler to implement and maintain, and won't lose any efficiency other than some memory cost for storing the samples.

**Comment by xukai92** [comment]
> I think it's better to keep the samples during adaption, and optionallly drop them when sampling finishes.

What I mean here is that if `drap_warmup=true` is set, we do not need to *first* store them *then* drop them. Instead, we can avoid storing them completely. See my PR https://github.com/TuringLang/AdvancedHMC.jl/pull/108.

**Comment by xukai92** [comment]
Closed by #108.
