### ISSUE TITLE
sample in this package and Distributions

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/AdvancedHMC.jl#42]
Both this package and `Distributions.jl` define a `sample` function, as opposed to this package extending `Distributions.jl`'s `sample` function with new methods. This causes a name clash which, given that these packages will likely be used to together a lot, is annoying. Should we maybe extend `Distributions.jl`'s `sample` rather than define our own?

**Comment by xukai92** [comment]
`StatsBase.sample` sounds better. We don't want unnecessary dependency on `Distributions`
