### ISSUE TITLE
Instantiation of new `AbstractMetric`s

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/AdvancedHMC.jl#45]
We currently have a method for each `AbstractMetric` which enables us to make another instance of the metric of the following form:
```julia
metric = ...
new_metric_of_same_type = metric(inverse_mass_matrix)
```
Why do we need such a method?

**Comment by xukai92** [comment]
This is for adaptation, during which we create a new `metric` based on the new M inverse. Hong and I believe make metric immutable instead of change in place would make code easier to maintain.

**Comment by willtebbutt** [comment]
I see -- I'm fully on board with the motivation for this, but I don't know that I think the current interface is ideal.

In particular, it's not clear to me why calling an object of type `AbstractMetric` should create another object of type `AbstractMetric` -- I would naively have expected the evaluation of a metric to take two elements from the corresponding space and compute the distance between them. Would you consider renaming this to something more informative?

I do appreciate that I'm being a bit pedantic...

**Comment by xukai92** [comment]
Yes I'm open to rename it.
