### ISSUE TITLE
[RFC]: notations used in this package

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#48]
At the moment, we are using the following notations:

- `logπ` - log target distribution
- `∂logπ∂θ` - gradient
- `prop` - transitioning kernel 
- `θ_init` - initial value for sampling states / parameters

I think this can be improved by

- `∂logπ∂θ` ==> `∇logπ` 
- `prop`  ==> `κ` (kappa) or `τ` (tau) - MH transitioning kernel
- `θ` - parameters, `r` - momentum
- `θ_init` ==> `θ₀` (theta_{0}), `r_init` ==> `r₀` (r_{0})
- `z` := `(θ, r)`   - `(position, momentum)` pair

Any other notations missing?

**Comment by willtebbutt** [comment]
I completely agree with all of @yebai 's proposals. Couple of quick comments:

- I would prefer `τ` to kappa, but don't have a hugely strong feeling either way.
- By `q₀`, do you mean `q₀` or `r₀`?

If the above are resolved, I'm happy :slightly_smiling_face:

**Comment by yebai** [comment]
> By q₀, do you mean q₀ or r₀?

should be ` r₀`.

**Comment by xukai92** [comment]
Nice call! I agree we with these notations! Let's change to them.

**Comment by xukai92** [comment]
@yebai Did we have similar agreement on things like `\epsilon` used in Turing?

**Comment by yebai** [comment]
> @yebai Did we have similar agreement on things like \epsilon used in Turing?

how about using the symbol `ϵ`?

**Comment by xukai92** [comment]
`\epsilon` is `ϵ`
