### ISSUE TITLE
Identify divergent transition

### ISSUE THREAD

**Issue by jonasmac16** [TuringLang/AdvancedHMC.jl#50]
I was speaking with Kai about this and agreed it would be good to be able to identify divergence of a particular transition (Sec. 6.2 in [here](https://arxiv.org/pdf/1701.02434.pdf) ) allowing us to identify pathologies which may bias the posterior sample.

**Comment by xukai92** [comment]
Thanks for raising this issue! Sec. 6.2 in fact corresponds to https://github.com/TuringLang/AdvancedHMC.jl/blob/master/src/proposal.jl#L104 in the codebase (not obviously to catch as we are following the alg. description in the original NUTS paper). After the current open PR (https://github.com/TuringLang/AdvancedHMC.jl/pull/49), in which the interface to return this divergence number is set up, is merged, we plan to introduce a type for this divergence information and hopefully this issue will be solved by then.

**Comment by yebai** [comment]
Is this resolved now?
