### ISSUE TITLE
Update gradient function to return both value and gradient

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#56]
Return value doesn't introduce any cost and it would save some computation for place where value is needed right after gradient evaluation.

**Comment by chriselrod** [comment]
I am trying the library now.

For now I defined a (`mutable struct`) storage buffer that stores the logdensity, gradient, and vector used for calling them. 
The gradient and density functions check if the new parameter vector `===` the old one. If not, update the stored ValueGradient object and params.
If they are `===`, simply return the old.

This relies on AdvancedHMC.jl not mutating the parameter vectors.
If the library is later updated to work in place, without yet resolving this issue, I'll use `==` instead, and copy data over. It'd take a lot of failed checks to be slower than evaluating the log density (200 microseconds vs 73 parameters).

As an off topic aside, my first impressions of `AdvancedHMC.jl` are very positive. The library seems very fast -- which probably mostly means that the trees are relatively shallow.
I was struggling to get convergence at all, but this library seems to converge rather well. So far it looks like I'm having more success with a `DiagEuclideanMetric` than a `DenseEuclideanMetric`.

Besides being fast and actually converging, I love `progress=true` while sampling. When my model fails to converge, the step size shrinks to `< 1e-4`. It's nice to get a live update on that and acceptance rate while mucking with settings.

**Comment by xukai92** [comment]
Thanks for sharing this trick. The issue is likely to be resolved before the mutation PR got in - so here is no worries.

**Comment by xukai92** [comment]
Closed by PR #79.
