### ISSUE TITLE
HMC: Multinomial Sampling Instead of Slice Sampling

### ISSUE THREAD

**Issue by wesselb** [TuringLang/AdvancedHMC.jl#62]
As mentioned on page 59 in [1], multinomial sampling instead of slice sampling may provide an improvement in overall performance.

[1] https://arxiv.org/abs/1701.02434

**Comment by xukai92** [comment]
@yebai Do you think it make more sense for us to implement this first so that our algorithm is the same as Stan and DHMC before we try to find a possible bug?

**Comment by yebai** [comment]
It sounds good to me, although I suspect that the bug is in the `build_tree` part of the code. Maybe we can improve the code a bit by implementing the `multinomial` sampling scheme.

**Comment by xukai92** [comment]
Closed by PR #79.
