### ISSUE TITLE
Re-name HMC.jl to HMCCore.jl?

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#8]
As this package mainly aim to provide robust building blocks for HMC (instead of providing a robust `sample` interface directly), may be we want to re-name it? @yebai @trappmartin

**Comment by trappmartin** [comment]
If this will be a registered package you might have to spell out HMC. It’s a community rule and people sometimes  require it for getting packages registered.

Maybe HMCFuns

**Comment by yebai** [comment]
How about `AdvancedHMC`? I think this is more descriptive and general.

**Comment by xukai92** [comment]
I'd prefer a name which indicates this is not a package which aims to provide final samplers but building blocks for HMC. Or actually we may want to provide that - now sure?

**Comment by yebai** [comment]
> Or actually we may want to provide that - now sure?

yes, let's try to provide an HMC package which can be used outside Turing (e.g. Soss and Mamba)!
