### ISSUE TITLE
More unit tests for HMC building blocks

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#84]
- [x] metrics
- abstraction related to NUTS
  - [x] tree sampler
  - [x] termination critera
  - [x] full binary tree

**Comment by yebai** [comment]
More unit tests to resolve the ESS issue (https://github.com/TuringLang/Turing.jl/issues/840). 

Some standard unit tests that we should try:

1. compare AHMC and DHMC on a set of hand-coded target distributions (e.g. https://github.com/TuringLang/Turing.jl/issues/840). This allows us to rule out potential interactions with `Bisectors`, `VarInfo`.

2. compare ESS of HMC configurations with mass matrix adaptation, step-size adaptation, u-turn independently, one at a time. This would allow us to rule out interactions between step-size, preconditioning and u-turn termination. 

3. compare AHMC and DHMC with vanilla HMC with manual step-size and no preconditioning. This allows us to rule out potential bugs with leapfrog integrator, MH correction etc.
