### ISSUE TITLE
How to convert the output into a MCMCChains `Chains`

### ISSUE THREAD

**Issue by Vaibhavdixit02** [TuringLang/AdvancedHMC.jl#89]

**Comment by Vaibhavdixit02** [comment]
Oops, pressed enter there before I meant to!

So I am working with AdvancedHMC using it for sampling and using pretty much the setup in the Readme, I was wondering what would be a convenient way to cover the samples into a MCMCChains' `Chains`, I want all the goodness of plots and diagnostics that MCMCChains gives!

**Comment by cpfiffer** [comment]
I'm assuming that you have a vector of vectors representing the samples AdvancedHMC returns, called `samples`. Probably the quickest way to do this is just

```julia
# Note that I'm taking the transpose here, using '
sample_arr = Array(hcat(samples...)')
chain = Chains(sample_arr)
```

If you know what the parameters are called, you can also pass in a vector of strings in the second argument:

```julia
names_list = ["mu", "sigma", "theta"]
sample_arr = Array(hcat(samples...)')
chain = Chains(sample_arr, names_list)
```

That said, I'm honestly surprised that MCMCChains does not have a constructor to handle the vector-of-vectors format, so I have opened a PR [over there](https://github.com/TuringLang/MCMCChains.jl/pull/114) to handle this such that you can just call `Chains(samples)` and it'll just work. It'll be a bit before I merge it over and publish it, so for now you can do the `Array(hcat(samples...)')` trick I used above.

**Comment by Vaibhavdixit02** [comment]
@cpfiffer thank you for the quick response. Actually 
```
sample_arr = Array(hcat(samples...)')
chain = Chains(sample_arr)
```
doesn't really work as well, `Chains` always expects a 3-dimensional array it seems. That was actually the issue I was facing earlier as well, maybe a 2 dimensional array (I am guessing this is because I am dealing with a single chain) should be handled as well by `Chains`?

**Comment by cpfiffer** [comment]
My bad, I hadn't released the 2d `Array` constructor either. I have one test to fix and then I'll try and get a release out.

There's a really dumb hack for this if you don't want to wait for a formal release:

```julia
# Force this to a 3D array.
sample_arr = Array(vcat(samples...)')[:,:,:]
```

**Comment by Vaibhavdixit02** [comment]
I did get it working, just thought it would be a nice thing to have. Thanks for the help! 🙂

**Comment by cpfiffer** [comment]
These are pretty useful constructors to have -- thanks for asking for this. I'll close this issue once I've issued a release on MCMCChains so you don't have to do any weird manipulations like the above.

**Comment by Vaibhavdixit02** [comment]
Awesome, thanks!

**Comment by cpfiffer** [comment]
MCMCChains 0.3.11 has just been released, which contains constructors that accept a vector-of-vectors and two dimensional arrays. Thanks for opening an issue, and let me know over at the MCMCChains repo if this doesn't work for you.
