### ISSUE TITLE
Potential improvement for U-Turn detection

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#94]
See https://github.com/stan-dev/stan/pull/2800 and https://discourse.mc-stan.org/t/nuts-misses-u-turns-runs-in-circles-until-max-treedepth/9727/36?u=betanalpha

**Comment by xukai92** [comment]
Related PyMC3 PR: https://github.com/pymc-devs/pymc3/pull/3605

**Comment by xukai92** [comment]
Related issue in DHMC.jl: https://github.com/tpapp/DynamicHMC.jl/issues/115

**Comment by xukai92** [comment]
Closed by https://github.com/TuringLang/AdvancedHMC.jl/pull/207.
