### ISSUE TITLE
Better names for sampling methods from trees

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AdvancedHMC.jl#99]
See https://github.com/TuringLang/AdvancedHMC.jl/commit/26aabb59c819d6b238aa70b80b692fdb51462934#commitcomment-34976303

**Comment by xukai92** [comment]
Related discussion: https://github.com/TuringLang/AdvancedHMC.jl/pull/91#issuecomment-522636114

**Comment by yebai** [comment]
Maybe we can remove `Slice` and `Multinomial` from exports? These exports are only useful for expert-users, so we might not want to export anyway.

**Comment by xukai92** [comment]
I prefer to rename them for several reasons. 
- Users have to use `AdvancedHMC.Slice` if we don't export them.
- AdvancedHMC IS for "expert-users".

Some options:
1. Go for the simplicity: `Multinomial` -> `Multi`
2. Go for self-contained: `TrajectoryMultinomialSampler` and `TrajectorySliceSampler`

Any thoughts?

**Comment by xukai92** [comment]
Option 3:

Define `@enum TrajectorySampler slice multinomial` and somehow dispatch over them. (Might be tricky?)

**Comment by yebai** [comment]
I mean in most cases we will use the default NUTS configuration, so maybe it’s ok to remove Slice/Multinomial from exports. Also, the user can still explicitly import these names if needed.

**Comment by yebai** [comment]
we can consider create a sugar syntax, e.g. NUTS(...) will create a NUTS sampler with Multinomial sampler.

**Comment by yebai** [comment]
Alternatively, we can shorten `SliceTrajectorySampler` to `SliceTS`, similarly `MultinomialTS` and `MetropolisTS`.

**Comment by xukai92** [comment]
I like this `???TS` proposal! Let's do this.

**Comment by yebai** [comment]
Closed by #114.
